udvis:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ var('DBT_USER') }}"
      password: "{{ var('DBT_PASS') }}"
      port: 5432
      dbname: storage
      schema: public
      threads: 4
